[package]
name = "btf_query"
version = "0.0.0"
edition.workspace = true
authors = ["Daniel Müller <deso@posteo.net>"]
license = "LGPL-2.1-only OR BSD-2-Clause"

[dependencies]
libbpf-rs = { path = "../../libbpf-rs" }

[lints]
workspace = true
